
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-mprd-config
  namespace: dev-mprd
data:
  mprd-db: "prod32"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-mprd-config
  namespace: dev-mprd
data:
  my.cnf: |-
    [client]
    default-character-set=latin1
    ## WARNING: This file is managed by a Config Management Tool. Changes to this file will be overwritten. ##

    [mysql]
    no-auto-rehash
    local-infile=1

    [mysqld]
    datadir=/var/lib/mysql
    socket=/var/lib/mysql/mysql.sock

    #---------------
    # Basic Settings
    #---------------
    bind-address          = 0.0.0.0
    character_set_server  = latin1 #utf8
    collation_server      = latin1_swedish_ci #utf8_unicode_ci
    skip-character-set-client-handshake

    connect_timeout       = 10
    # language              = /usr/share/mysql/english
    old_passwords         = 0

    #disable_auto_rehash

    #skip-slave-start

    skip-external-locking

    #secure-file-priv=''
    # skip-name-resolve

    # skip-networking

    wait_timeout          = 28800

    explicit_defaults_for_timestamp


    #------------
    # Fine Tuning
    #------------
    back_log                        = 50
    bulk_insert_buffer_size         = 64M #32M

    group_concat_max_len            = 4096
    join_buffer_size                = 8M
    key_buffer_size                 = 25GB
    lower_case_table_names          = 1
    max_allowed_packet              = 512M
    max_connect_errors              = 100000
    max_connections                 = 2000
    max_heap_table_size             = 256M #64M
    max_sp_recursion_depth          = 50
    open-files-limit                = 16384
    port_open_timeout               = 5
    query_alloc_block_size          = 16K
    read_buffer_size                = 2M #1M
    read_rnd_buffer_size            = 10M
    sort_buffer_size                = 64M #2M
    sql-mode                        = NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION #TRADITIONAL

    table_open_cache                = 4096 #2048 #1024

    thread_cache_size               = 32 #8
    thread_stack                    = 192K
    tmp_table_size                  = 256M #64M
    transaction_isolation           = READ-COMMITTED


    binlog_gtid_simple_recovery     = 1


    #--------------------------
    # Query Cache Configuration
    #--------------------------
    query_cache_limit = 2M #2M
    query_cache_size  = 64M #0
    query_cache_type  = 1 #0

    #-----------------
    # Logging Settings
    #-----------------
    #general_log_file    = /db/p/enc/v1/admin/ENCSQLP1/logs/general.log
    #general_log_file    = /data/mysql/logs/general.log


    log_output          = file


    long_query_time     = 10
    slow_query_log      = 1
    #slow_query_log_file = /db/p/enc/v1/admin/ENCSQLP1/logs/mysql_slow.log
    #slow_query_log_file = /data/mysql/logs/mysql_slow.log

    auto_increment_increment  = 2 #10
    auto_increment_offset     = 1
    binlog_cache_size         = 8M #1M

    binlog_format             = ROW
    expire_logs_days          = 3 #7
    #log-bin                   = /db/p/enc/v2/archlog/ENCSQLP1/bctlpencsql01_bin
    #log-bin                   = /data/mysql/bctlpencsql01_bin
    #log_bin_index             = /db/p/enc/v2/archlog/ENCSQLP1/bctlpencsql01_bin.index
    #log_bin_index             = /data/mysql/bctlpencsql01_bin.index

    log_bin_trust_function_creators = 1

    log_slave_updates

    max_binlog_size           = 1G
    #relay-log                 = /db/p/enc/v2/archlog/ENCSQLP1/bctlpencsql01_relay_bin
    #relay_log_index           = /db/p/enc/v2/archlog/ENCSQLP1/bctlpencsql01_relay_bin.index
    #relay_log_info_file       = /db/p/enc/v2/archlog/ENCSQLP1/bctlpencsql01_relay_log.info
    #relay-log                 = /data/mysql/bctlpencsql01_relay_bin
    #relay_log_index           = /data/mysql/bctlpencsql01_relay_bin.index
    #relay_log_info_file       = /data/mysql/bctlpencsql01_relay_log.info
    skip_slave_start          = False

    slave_compressed_protocol = 1
    sync_binlog               = 0 #1

    report_host                     = bctlpencsql01
    slave-net-timeout               = 30


    #slave-skip-errors
    slave_parallel_workers          = 0
    slave_allow_batching            = 1
    slave_checkpoint_period         = 5000
    slave_checkpoint_group          = 5120
    slave_pending_jobs_size_max     = 104857600
    # for better crash recovery
    master_info_repository          = 'table'
    relay_log_info_repository       = 'table'

    relay_log_recovery              = 0

    #----------------
    # MyISAM settings
    #----------------
    myisam_max_sort_file_size = 20G #10G
    myisam_repair_threads     = 8 #4
    myisam_sort_buffer_size   = 4G #32M

    #----------------
    # InnoDB settings
    #----------------
    default_storage_engine          = MyISAM
    default_tmp_storage_engine      = MyISAM


    #######
    optimizer_switch                = index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,engine_condition_pushdown=on,index_condition_pushdown=on,mrr=on,mrr_cost_based=on,block_nested_loop=off,batched_key_access=off,materialization=on,semijoin=on,loosescan=on,firstmatch=on,duplicateweedout=on,subquery_materialization_cost_based=on,use_index_extensions=on,condition_fanout_filter=on,derived_merge=on

    #---------------
    # SSL Settings #
    #---------------
    ssl_cipher = ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
    #ssl-ca=/db/p/enc/v1/admin/ENCSQLP1/certs/star.risk.regn.net.pem
    #ssl-cert=/db/p/enc/v1/admin/ENCSQLP1/certs/star.risk.regn.net.pem
    #ssl-key=/db/p/enc/v1/admin/ENCSQLP1/certs/star.risk.regn.net.key.pem
    #ssl-ca=/data/mysql/certs/star.risk.regn.net.pem
    #ssl-cert=/data/mysql/certs/star.risk.regn.net.pem
    #ssl-key=/data/mysql/certs/star.risk.regn.net.key.pem

    #-------------------
    # Performance Schema
    #-------------------
    performance_schema = ON


    plugin-load="audit_log=audit_log.so;auth_pam=auth_pam.so;auth_pam_compat=auth_pam_compat.so;auth_socket=auth_socket.so"
    #audit_log_file=/db/p/enc/v1/admin/ENCSQLP1/logs/audit.log
    #audit_log_file=/data/mysql/logs/audit.log
    audit_log_rotations=5
    audit_log_rotate_on_size=256M
    audit_log_format=NEW
    audit_log_policy=QUERIES
    audit_log_include_databases='information_schema'
    audit_log_exclude_commands='error,insert,update,delete,set_option,change_db,prepare_sql,execute_sql,show_variables,show_status,call_procedure,show_collations,commit,execute,show_slave_status,show_master_status'
    # audit_log_exclude_accounts="dbpenc@%,dbadmin@%,'spider_app'@'%','zenoss'@'%','hbmon'@'%','lbmon'@'%',haproxy@%,repl@%,'repl'@'%',dbamaint@'%'"


    #### Custom Variables Start #####
    #max_connections = 1024
    #max_binlog_size = 1G
    #innodb_fast_shutdown = 1
    #### Custom Variables Ends#####

    init_connect = 'call dba_audit.simpleproc(@out_value); set session SQL_SELECT_LIMIT=@out_value'

    log_error_verbosity = 2

---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: init-mprd-config
#   namespace: dev-mprd
# data:
#   init-cm.sql: |-
#     CREATE USER IF NOT EXISTS '${SVC_ACC_UID}'@'%' IDENTIFIED BY '${SVC_ACC_PWD}' ;
#     GRANT SELECT ON prod32.* TO '${SVC_ACC_UID}'@'%' ;
#     ALTER USER '${SVC_ACC_UID}'@'%' PASSWORD EXPIRE NEVER ;
# ---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: mprd
  namespace: dev-mprd
  labels: 
    app: mprd
spec:
  serviceName: mprd
  replicas: 1
  selector:
    matchLabels:
      app: mprd
  template:
    metadata:
      labels:
        app: mprd
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: mprd
        image: mysql:5.7 # gitlab.ins.risk.regn.net:4567/hcp-enclarity/providerpoint/providerpointbatch/percona:5.7.31-34.1.el7

        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
      
        args:
          - "--default-authentication-plugin=mysql_native_password"
          - "--ignore-db-dir=lost+found"
          - "--user=1000:1000"
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: env-mprd-config
                key: mprd-db
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: root-pwd
          - name: SVC_ACC_UID
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: svc-acc-uid
          - name: SVC_ACC_PWD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: svc-acc-pwd
        ports:
        - containerPort: 3306
          name: mprd

        volumeMounts:
        - name: volume
          mountPath: /nfs/mprd
          readOnly: true
        - name: data
          mountPath: /var/lib/mysql
        - name: init-db
          mountPath: /docker-entrypoint-initdb.d
        # - name: my-config
        #   mountPath: /etc/my.cnf
        #   subPath: my.cnf

        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 128Mi
    
        lifecycle:
          postStart:
            exec:
              command: 
              - "/bin/sh"
              - "-c"
              - >
                while [ ! -d /var/lib/mysql/${MYSQL_DATABASE} ]; do sleep 1; done;
                cp -u --preserve=all /nfs/mprd/${MYSQL_DATABASE}/*.* /var/lib/mysql/${MYSQL_DATABASE}/;
                chown -R 1000:1000 /var/lib/mysql/${MYSQL_DATABASE};

      initContainers:
      - name: init-mprd
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
        image: busybox:1.28
        command: ['sh', '-c' ]
        args:
        - echo "Staring";
          echo "CREATE USER IF NOT EXISTS '${SVC_ACC_UID}'@'%' IDENTIFIED BY '${SVC_ACC_PWD}';" > /docker-entrypoint-initdb.d/init.sql;
          echo "GRANT SELECT ON ${MYSQL_DATABASE}.* TO '${SVC_ACC_UID}'@'%';" >> /docker-entrypoint-initdb.d/init.sql;
          echo "ALTER USER '${SVC_ACC_UID}'@'%' PASSWORD EXPIRE NEVER;" >> /docker-entrypoint-initdb.d/init.sql;
          chown -R 1000:1000 /docker-entrypoint-initdb.d;
          ls -la;
          ls -l /docker-entrypoint-initdb.d/;
          echo "done";
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: env-mprd-config
                key: mprd-db
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: root-pwd
          - name: SVC_ACC_UID
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: svc-acc-uid
          - name: SVC_ACC_PWD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: svc-acc-pwd
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: init-db
          mountPath: /docker-entrypoint-initdb.d

      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: nfs-mprd
      - name: init-db
        emptyDir: {}
      - name: my-config
        configMap:
          name: my-mprd-config
          items:
          - key: my.cnf
            path: my.cnf
      # - name: init-db
      #   configMap:
      #     name: init-mprd-config

      
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: default # For Prod managed-premium
      resources:
        requests:
          storage: 150Gi
          
---
apiVersion: v1
kind: Service
metadata:
  name: mprd
  namespace: dev-mprd
spec:
  ports:
  - port: 3306
  clusterIP: None
#  publishNotReadyAddresses: true
  selector:
    app: mprd
---
