{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "qpid.serviceAccountName" . }}
  labels:
    {{- include "qpid.labels" . | nindent 4 }}
   {{- end }}
