apiVersion: v1
kind: Service
metadata:
  name: {{ include "qpid.fullname" . }}
  namespace: dev-qpid
  labels:
    {{- include "qpid.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      
  selector:
    {{- include "qpid.selectorLabels" . | nindent 4 }}
