apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpmatch
  namespace: dev-matcher
  labels:
    app: dpmatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dpmatch
  template:
    metadata:
      labels:
        app: dpmatch
    spec:
      containers:
      - name: dpmatch
        image: gitlab.ins.risk.regn.net:4567/hcp-enclarity/providerpoint/providerpointbatch/dpmatch:6.7.191
        imagePullPolicy: Always
#      imagePullSecrets:
#      - name: repository-secret
        env:
        - name: MYSQL_HOST
          value: 'mprd.dev-mprd.svc.cluster.local'
        - name: QPID_HOST
          value: 'qpid.dev-qpid.svc.cluster.local'
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
