apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "quid.fullname" . }}
  namespace: dev-qpid
  labels:
    {{- include "quid.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  serviceName: qpid
  selector:
    matchLabels:
      {{- include "quid.selectorLabels" . | nindent 6 }}
  template:
    metadata:     
      labels:
        {{- include "quid.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "quid.serviceAccountName" . }}
      #securityContext:
      #  {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5672
              
          #livenessProbe:
          #  httpGet:
           #   path: /
           #   port: http
         # readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      #{{- with .Values.nodeSelector }}
      #nodeSelector:
      #  {{- toYaml . | nindent 8 }}
      #{{- end }}
      #{{- with .Values.affinity }}
      #affinity:
     #   {{- toYaml . | nindent 8 }}
     # {{- end }}
      #{{- with .Values.tolerations }}
     # tolerations:
      #  {{- toYaml . | nindent 8 }}
      #{{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/qpid
          readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl -v --silent http://localhost:4040/ 2>&1 | grep $HOSTNAME

      - name: {{ .Chart.Name }}-le
        image: "k8s.gcr.io/leader-elector:0.5"
        args:
        - --election=qpid
        - --http=0.0.0.0:4040
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4040
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: default # For Prod managed-premium
      resources:
        requests:
          storage: 20Gi
